config/routes.rb
Cooker::Application.routes.draw do

    devise_for :users

    root 'recipes#index'

    resources :items do
      post :increase, on: :member
      post :decrease, on: :member
    end

    resources :products do
      resources :items
      post :increase, on: :member
      post :decrease, on: :member
    end

    resources :recipes do
      resources :parts, only: [:new, :create]
      post :produce, on: :member
      patch :produce, on: :member
    end

    resources :parts, only: [:show, :edit, :update, :destroy]

end

app/models/part.rb
class Part < ActiveRecord::Base

  belongs_to :recipe
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates_associated :product

  def name
    product = self.product
    product.name
  end

  def unit
    product = self.product
    product.unit
  end

  def recipe_name
    recipe = self.recipe
    recipe.name
  end

  def avaliable
    user = User.current
    self.reload
    item = user.items.where(product_id: self.product.id).first
    if item.nil?
      0
    else
      item.quantity / self.quantity
    end
  end

  def spend(count)
    item = User.current.items.where(product_id: self.product.id).first
    scount = self.quantity * count
    item.decrease(scount)
  end


end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
    @recipe = @part.recipe
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
    @recipe = @part.recipe
  end

  # POST /parts
  # POST /parts.json
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @part = @recipe.parts.create(params[:part].permit(:quantity, :product_id))

    respond_to do |format|
      if @part.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Part was successfully created.' }
        format.json { render action: 'show', status: :created, location: @part }
      else
        format.html { render action: 'new' }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    @recipe = @part.recipe
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to recipe_path(@recipe), notice: 'Part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render controller: 'recipes', action: 'edit' }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @recipe = @part.recipe
    @part.destroy
    respond_to do |format|
      format.html { redirect_to recipe_path(@recipe) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:quantity, :recipe_id, :product_id)
    end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= bootstrap_form_for([@recipe, @recipe.parts.build]) do |f| %>

    <%= f.text_field :quantity %>

    <%= f.collection_select :product_id, Product.all, :id, :name %>

    <%= f.submit "Save Part" %>

<% end %>

app/views/parts/edit.html.erb
<div class='col-md-6'>

  <h1>Editing part</h1>

    <%= render 'form' %>

  <br>

  <%= link_to 'Show', @part, class: 'btn btn-large btn-info' %> |
</div>

<div class='col-md-6'>

  <p id="notice"><%= notice %></p>

  <h2><%= @recipe.name %></h2>

    <p><%= @recipe.description %></p>
    <p>Вес: <%= @recipe.quantity %> <%= @recipe.unit %></p>
    <p>Доступно: <%= @recipe.avaliable %></p>

  <br>

  <td><%= link_to 'Show', recipe_path, class: 'btn btn-info btn-large' %></td>

</div>

app/views/parts/index.html.erb
<div class="col-md-6">
  <h1>Ингридиенты</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>id</th>
        <th>Название</th>
        <th>Количество</th>
        <th>Измеряется</th>
        <th>Рецепт</th>
      </tr>
    </thead>

    <tbody>
      <% @parts.each do |part| %>
        <tr>
          <td><%= part.name %></td>
          <td><%= part.quantity %></td>
          <td><%= part.unit %></td>
          <td><%= part.recipe_name %></td>
          <td><%= link_to 'Edit', edit_part_path(part.recipe, part), class: 'btn btn-primary btn-xs' %></td>
          <td><%= link_to 'Destroy', part_path(part.recipe, part), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Part', edit_recipe_path, class: 'btn btn-success' %>
</div>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_parts_path %>

app/views/parts/show.html.erb
<div class="col-md-6">

  <p id="notice"><%= notice %></p>

  <h2><%= @part.name %></h2>

  <ul>
    <li><%= @part.quantity %> <%= @part.unit %></li>
    <li><%= @part.unit %></li>
  </ul>

  <%= link_to 'Edit', edit_part_path(@part) %> |
  <%= link_to 'Back', recipe_parts_path(@recipe) %>

</div>