config/routes.rb
Cooker::Application.routes.draw do

    devise_for :users

    root 'recipes#index'

    resources :items do
      post :increase, on: :member
      post :decrease, on: :member
    end

    resources :products do
      resources :items
      post :increase, on: :member
      post :decrease, on: :member
    end

    resources :recipes do
      resources :parts, only: [:new, :create]
      post :produce, on: :member
      patch :produce, on: :member
    end

    resources :parts, only: [:show, :edit, :update, :destroy]

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  has_many :parts
  has_many :products, through: :parts

  validates :name, length: { in: 4..20 }, presence: true
  validates :description, length: { in: 4..255 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :unit, length: { in: 2..10 }, presence: true

  def avaliable
    self.reload
    pa = []
    self.parts.each do |p|
      a = p.avaliable
      pa.push a
      p pa
    end
    pa.min.to_i
  end

  def produce(count)
    parts = self.parts
    parts.each do |part|
      part.spend(count.to_i)
    end

    prd = Product.find_or_initialize_by(name: self.name, description: self.description, unit: self.unit)
    pcount = count*self.quantity

    unless prd.persisted?
      prd.quantity = self.quantity
      prd.generated = true
      prd.save
    end

    item = Item.find_or_initialize_by(user_id: User.current.id, product_id: prd.id)

    if item.persisted?
        p "есть немного"
        item.increase(pcount)
      else
        "ща попробуем!"
        item.quantity = pcount
        item.save
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :produce]
  before_filter :set_current_user

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @parts = @recipe.parts
    @avaliable = @recipe.avaliable
  end

  def produce
    count = recipe_count[:count].to_i
    @ra = @recipe.avaliable
    if (1..@ra) === count && @ra >= count
      @recipe.produce(count)
      redirect_to recipe_path(@recipe), notice: 'Успешно приготовлено!'
    elsif @ra < count
      redirect_to recipe_path(@recipe), alert: 'Требуется больше продуктов!'
    else redirect_to recipe_path(@recipe), alert: 'Фарш неводможно провернуть назад!!'
    end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  def parts
    @parts = @recipe.parts
  end

  # GET /recipes/1/edit
  def edit
    @parts = @recipe.parts
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.where(id: params[:id]).first
      render_404 unless @recipe
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :quantity, :unit, parts: [:product_id, :quantity] )
    end

    def recipe_count
      params.permit :count
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_addpart.html.erb
<h2>Add a part:</h2>
<%= bootstrap_form_for([@recipe, @recipe.parts.build]) do |f| %>

    <%= f.text_field :quantity %>

    <%= f.collection_select :product_id, Product.all, :id, :name %>

    <%= f.submit "Save Part" %>

<% end %>

app/views/recipes/_form.html.erb
<%= bootstrap_form_for(@recipe) do |f| %>


  <%= f.text_field :name %>
  <%= f.text_field :quantity %>
  <%= f.text_field :unit %>
  <%= f.text_area :description %>

  <%= f.submit "Save Recipe", class: "btn btn-success" %>

<% end %>
  <br>

app/views/recipes/_produce.html.erb
<%= bootstrap_form_tag url: produce_recipe_path, layout: :inline do |f| %>


    <%= f.select "count", options_for_select((1..3).step(1)), hide_label: true %>
    <%= f.submit "Приготовить", class: "btn btn-success" %>

    <% end %>

    <%= @avale %>

app/views/recipes/edit.html.erb
<div class='col-md-6'>
  <h1>Editing recipe</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @recipe %> |
  <%= link_to 'Back', recipes_path %>
</div>

<div class='col-md-6'>
  <br>
  <br>
  <br>
  <h3>Ингридиенты</h3>

  <table class="table table-hover">
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.name %></td>
        <td><%= part.quantity %></td>
        <td><%= part.product.unit %></td>
        <td><%= link_to 'Edit', edit_part_path(part), class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Destroy', part_path(part), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </table>

  <%= render 'addpart' %>

</div>

app/views/recipes/index.html.erb
<div class="col-md-6">
  <h1>Известные рецепты</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>id</th>
        <th>Название</th>
        <th>Количество</th>
        <th>Измеряется</th>
      </tr>
    </thead>

    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.id %></td>
          <td><%= link_to recipe.name, recipe_path(recipe) %></td>
          <td><%= recipe.quantity %></td>
          <td><%= recipe.unit %></td>
          <td>....</td>
          <td><%= link_to 'Show', recipe, class: 'btn btn-info btn-xs' %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe), class: 'btn btn-primary btn-xs' %></td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-success' %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

  <div class="col-md-6">
    <%= render 'form' %>

    <%= link_to 'Back to recipes', recipes_path, class: 'btn btn-large btn-primary', method: :get %>
  </div>

  <div class="col-md-6">
    <p class="text-info">
      <%= 'Создайте новый рецепт, заполнив все поля слева.' %>
    </p>
  </div>

app/views/recipes/parts.html.erb
<div class='col-md-6'>

  <br>
  <br>

  <p id="notice"><%= notice %></p>

  <h2><%= @recipe.name %></h2>

  <p><%= @recipe.description %></p>
  <p>Вес: <%= @recipe.quantity %> <%= @recipe.unit %></p>
  <p>Доступно: <%= @recipe.avaliable %></p>
  <br>
  <h3>Ингридиенты</h3>

  <table class="table table-hover">
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.name %></td>
        <td><%= part.quantity %></td>
        <td><%= part.product.unit %></td>

      </tr>
    <% end %>
  </table>

  <%= render 'addpart' %>

</div>

<div class='col-md-6'>

  <p> Чтобы верно указать расход продукта на рецепт, которому вы сейчас добавляете ингридиент, обратите внимание на то, в чем измеряются ваши продукты.</p>

  <%= render 'products/index' %>

</div>

app/views/recipes/show.html.erb
<div class='col-md-9'>

  <div class="panel panel-default">

    <div class="panel-heading"><h2><%= @recipe.name %></h2></div>

    <div class="panel-body">
      <p><%= @recipe.description %></p>
      <p>Вес: <%= @recipe.quantity %> <%= @recipe.unit %></p>
      <p>Доступно: <%= @avaliable %></p>
      <%= render 'produce' %>
    </div>

    <ul class="list-group">
      <li class="list-group-item">
        <h3>Ингридиенты</h3>
      </li>

    <% @parts.each do |part| %>

      <li class="list-group-item">
        <td><%= part.name %></td>
        <td><%= part.quantity %></td>
        <td><%= part.product.unit %></td>
        <td><%= 'Не хватает!' if part.avaliable < 1 %></td>
      </li>

    <% end %>

      <li class="list-group-item">
        <%= link_to 'Edit', edit_recipe_path(@recipe), class: 'btn btn-large btn-warning' %> |
        <%= link_to 'Back', recipes_path, class: 'btn btn-large btn-info' %>
      </li>
    </ul>

  </div>

</div>