config/routes.rb
Cooker::Application.routes.draw do

    devise_for :users

    root 'recipes#index'

    resources :items do
      post :increase, on: :member
      post :decrease, on: :member
    end

    resources :products do
      resources :items
      post :increase, on: :member
      post :decrease, on: :member
    end

    resources :recipes do
      resources :parts, only: [:new, :create]
      post :produce, on: :member
      patch :produce, on: :member
    end

    resources :parts, only: [:show, :edit, :update, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :parts
  has_many :recipes, through: :parts
  has_many :items
  has_many :users, through: :items

  validates :name, length: { in: 4..20 }, presence: true
  validates :description, length: { in: 4..255 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :unit, length: { in: 2..10 }, presence: true

  def item_increase(uid, count)
    item = Item.find_or_initialize_by(user_id: uid, product_id: prd.id)
    self.quantity += count
    self.update(quantity: self.quantity.round(2))
  end

  def increase(count)
    quantity = self.quantity += count
    self.update(quantity: quantity.round(2))
  end

  def decrease(count)
    self.quantity -= count
    self.update(quantity: self.quantity.round(2))
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :increase, :decrease]
  before_filter :set_current_user

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if signed_in?
      @items_owned = current_user.items
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if signed_in?
      @item = @product.items.owned.first
        if @item.nil?
          @quantity =  @product.name + ' пора купить, хотя бы несколько '
        else
          @quantity = @item.quantity
        end
    end
  end

  def increase
    @item = @product.items.owned.first
    @ct = CountType.new
    @ct.count = (product_count[:count]).to_i
    if @ct.valid?
      @item.increase(@ct.count)
      redirect_to @product, success:  'Продукт успешно добавлен'
    else
      redirect_to @product, error: 'Введите число больше нуля'
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.where(id: params[:id]).first
      render_404 unless @product
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :quantity, :unit, :description, :count)
    end

    def product_count
      params.permit(:count)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/admin/_form.html.erb
<br>
<%= bootstrap_form_for(@product) do |f| %>

  <%= f.text_field :name, label: "Название" %>
  <%= f.text_field :quantity, label: "Количество" %>
  <%= f.text_field :unit, label: "Измеряется в" %>
  <%= f.text_area :description, label: "Описание" %>

  <%= f.submit "Сохранить", class: "btn btn-success" %>

<% end %>
<br>

app/views/products/admin/_quantity.html.erb
<%= form_tag increase_product_path, method: :post, class: "form-inline"  do %>
  <div class="form-group">
    <%= text_field_tag :count %>
    <%= @product.unit %>
    <%= submit_tag "Добавить", class: "btn btn-success btn-sm" %>
  </div>
<% end %>

<br>

<%= form_tag decrease_product_path, method: :post, :class => "form-inline"  do %>
  <div class="form-group">
    <%= text_field_tag :count %>
    <%= @product.unit %>
    <%= submit_tag "Убавить", class: "btn btn-warning btn-sm" %>
  </div>
<% end %>

<br>

<h2>Добавить еще?</h2>
<%= bootstrap_form_for @item, url: {controller: 'products', action: 'increase'} do |f| %>

    <%= f.hidden_field :product_id, value: @product.id %>


    <%= i.text_field :count, append: @product.unit, hide_label: true  %>

    <p> <%= f.submit 'Добавить', class: 'btn btn-success'  %>
     или
    <%= link_to 'Удалить?', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></p>

<% end %>

app/views/products/admin/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<% back = 'Посмотреть на ' + @product.name %>
<%= link_to back, @product, class: 'btn btn-large btn-info' %> |
<%= link_to 'Back to products', products_path, class: 'btn btn-large btn-info', method: :get %>

app/views/products/admin/index.html.erb
<div class="col-md-6">
  <h1>Продукты as admin</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>id</th>
          <th>Название</th>
          <th>Количество</th>
          <th>Измеряется</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= link_to product.id, product_path(product) %></td>
            <td><%= product.name %></td>
            <td><%= product.quantity %></td>
            <td><%= product.unit %></td>
            <td>....</td>
            <td><%= link_to 'Show', product, class: 'btn btn-info btn-xs' %></td>
            <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary btn-xs' %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Создать продукт', new_product_path, class: 'btn btn-success'  %>
</div>

app/views/products/admin/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back to products', products_path, class: 'btn btn-large btn-primary', method: :get %>

app/views/products/admin/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @product.name %></h2>

<ul>
  <li><%= @product.quantity %> <%= @product.unit %></li>
  <li><%= @product.description %></li>
</ul>

<%= render 'quantity' %>

<%= link_to 'Back to products', products_path, class: 'btn btn-large btn-info', method: :get %>
 |
 <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-large btn-warning' %>