config/routes.rb
Cooker::Application.routes.draw do

    devise_for :users

    root 'recipes#index'

    resources :items do
      post :increase, on: :member
      post :decrease, on: :member
    end

    resources :products do
      resources :items
      post :increase, on: :member
      post :decrease, on: :member
    end

    resources :recipes do
      resources :parts, only: [:new, :create]
      post :produce, on: :member
      patch :produce, on: :member
    end

    resources :parts, only: [:show, :edit, :update, :destroy]

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }, presence: true

  scope :owned, -> { where(user_id: User.current.id) }

  def description
    product = self.product
    product.description
  end

  def name
    product = self.product
    product.name
  end

  def unit
    product = self.product
    product.unit
  end

   def increase(count)
    self.quantity += count
    self.update(quantity: self.quantity.round(2))
  end

  def decrease(count)
    self.quantity -= count
    self.update(quantity: self.quantity.round(2))
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :increase]

  # GET /items
  # GET /items.json
  def index
    @all_items = Item.all #for testing only
    if signed_in?
      @items = current_user.items
    else
      redirect_to new_user_session_path, alert: "Необходимо войти в систему, чтобы посмотреть Items"
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show

  end

  def increase
    count = item_count[:count].to_i
    @item.increase(count)
    redirect_to item_path(@item)
  end

  def decrease
    count = item_count[:count].to_i
    @item.decrease(count)
    redirect_to item_path(@item)
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @product = Product.find(params[:product_id])
    @item = current_user.items.new(item_params)
      if @item.save
        redirect_to @product, success: 'Item was successfully created.'
      else
        redirect_to @product, alert: 'Все проебал'
      end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, success: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit', notice: 'Попробуйте еще раз.' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:quantity, :product_id)
    end

    def item_count
      params.permit(:count)
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= bootstrap_form_for(@item) do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :quantity %>

    <%= f.collection_select :product_id, Product.all, :id, :name %>

    <%= f.submit "Save item" %>
  </div>
<% end %>

app/views/items/_quantity.html.erb
<%= form_tag increase_item_path, method: :post, class: "form-inline"  do %>
  <div class="form-group">
    <%= text_field_tag :count %>
    <%= @item.unit %>
    <%= submit_tag "Добавить", class: "btn btn-success btn-sm" %>
  </div>
<% end %>

<br>

<%= form_tag decrease_item_path, method: :post, :class => "form-inline"  do %>
  <div class="form-group">
    <%= text_field_tag :count %>
    <%= @item.unit %>
    <%= submit_tag "Убавить", class: "btn btn-warning btn-sm" %>
  </div>
<% end %>

<br>

<td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="col-md-6">
  <h1>Мои продукты</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Название</th>
        <th>Количество</th>
        <th>Измеряется</th>
        <th>Владелец</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.quantity %></td>
          <td><%= item.unit %></td>
          <td><%= item.user.id %></td>
          <td><%= link_to 'Show', item, class: 'btn btn-info btn-xs' %></td>
          <td><%= link_to 'Edit', edit_item_path(item), class: 'btn btn-primary btn-xs' %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Item', new_item_path, class: 'btn btn-success' %>

  <h1>Все продукты</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Название</th>
        <th>Количество</th>
        <th>Измеряется</th>
        <th>Владелец</th>
      </tr>
    </thead>

    <tbody>
      <% @all_items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.quantity %></td>
          <td><%= item.unit %></td>
          <td><%= item.user.id %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @item.name %></h2>

<ul>
  <li><%= @item.quantity %> <%= @item.unit %></li>
  <li><%= @item.description %></li>
</ul>

<%= render 'quantity' %>

<%= link_to 'Back to items', items_path, class: 'btn btn-large btn-info', method: :get %>
 |
 <%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-large btn-warning' %>